services:
  # C# Web API Core (Docker)
  - type: web
    name: portfoland-web
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: portfoland-db
          property: connectionString
      - key: AllowedOrigins__0
        value: https://Sertoriel-site.vercel.app # Atualizaremos com o link real depois
      - key: Jwt__Key
        sync: false
      - key: AdminLogin__Username
        sync: false
      - key: AdminLogin__Password
        sync: false

databases:
  # PostgreSQL DB (Managed by Render)
  - name: portfoland-db
    plan: free
    postgresMajorVersion: "16"