// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfol.Api.Data;

#nullable disable

namespace Portfol.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310170410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Portfol.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BgBorderClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Techs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BgBorderClass = "border-blue-500/30",
                            Category = "Backend & Ferramentas",
                            ColorClass = "text-blue-400",
                            FullDescription = "Desenvolvido para otimizar o fluxo de monitoramento de dados em sistemas de mensageria...",
                            ShortDescription = "Ferramenta para debug e análise de logs de chatbots.",
                            Techs = "[\"Python\",\"PHP\",\"Laravel\"]",
                            ThumbnailUrl = "",
                            Title = "TwilCollector"
                        },
                        new
                        {
                            Id = 2,
                            BgBorderClass = "border-purple-500/30",
                            Category = "Game Development",
                            ColorClass = "text-purple-400",
                            FullDescription = "Focada em engajamento e experiência do usuário em ambientes educacionais, utilizando mecânicas de jogos para retenção de conhecimento.",
                            ShortDescription = "Plataforma de gamificação mobile imersiva.",
                            Techs = "[\"Unity\",\"C#\",\"Mobile UI\"]",
                            ThumbnailUrl = "",
                            Title = "Ubiqua Universe!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
