// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfol.Api.Data;

#nullable disable

namespace Portfol.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfol.Api.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentEn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryEn")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Portfol.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BgBorderClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryEn")
                        .HasColumnType("text");

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadLink")
                        .HasColumnType("text");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullDescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("GithubLink")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescriptionEn")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Techs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleEn")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BgBorderClass = "border-blue-500/30",
                            Category = "Backend & Ferramentas",
                            ColorClass = "text-blue-400",
                            FullDescription = "Desenvolvido para otimizar o fluxo de monitoramento de dados em sistemas de mensageria...",
                            ShortDescription = "Ferramenta para debug e análise de logs de chatbots.",
                            Techs = new List<string> { "Python", "PHP", "Laravel" },
                            ThumbnailUrl = "",
                            Title = "TwilCollector"
                        },
                        new
                        {
                            Id = 2,
                            BgBorderClass = "border-purple-500/30",
                            Category = "Game Development",
                            ColorClass = "text-purple-400",
                            FullDescription = "Focada em engajamento e experiência do usuário em ambientes educacionais, utilizando mecânicas de jogos para retenção de conhecimento.",
                            ShortDescription = "Plataforma de gamificação mobile imersiva.",
                            Techs = new List<string> { "Unity", "C#", "Mobile UI" },
                            ThumbnailUrl = "",
                            Title = "Ubiqua Universe!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
